# 执行时排除掉的规则
 disabled_rules:
   - force_cast
   - control_statement
   - trailing_whitespace
   - shorthand_operator
   - large_tuple
   - empty_count
   - for_where
   - cyclomatic_complexity
   - function_parameter_count
   - multiple_closures_with_trailing_closure
   - legacy_constructor
   - nesting
   - block_based_kvo
 opt_in_rules: # 一些规则仅仅是可选的
   - empty_count
#   - missing_docs
 included: # 执行 linting 时包含的路径。如果出现这个 `--path` 会被忽略。
   - ../
 excluded: # 执行 linting 时忽略的路径。 优先级比 `included` 更高。
   - Pods
# 可配置的规则可以通过这个配置文件来自定义
 line_length:  #一行最大长度
   warning: 200
   ignores_comments: true
 function_body_length: 200 #函数体行数
 type_body_length: #比如定义一个enum或struct的类型体长度
   warning: 400 # warning
# 或者也可以同时进行显式设置
 file_length:
   warning: 1500
 vertical_parameter_alignment_on_call: true #函数参数对齐
# 命名规则可以设置最小长度和最大程度的警告/错误
 switch_case_alignment: true #对齐
# 此外它们也可以设置排除在外的名字
 type_name: #类型名
   min_length: # 只是警告
     warning: 2
   max_length: # 警告和错误
     warning: 50
 identifier_name:
   min_length: #最小长度
     warning: 2 # 只有错误
   max_length: #最大长度
     warning: 40 #只有错误
   excluded: # 排除某些名字
     - id
     - URL
   allowed_symbols: ["_"]
 reporter: "xcode" # 报告类型 (xcode, json, csv, checkstyle, junit, html, emoji)
